export const memberTypes = ['Fan / Audiophile','Artist / Musician','Music Industry Professional','Business / Venue / Organization'];
export const professionalTypes = ['Producer','Booking Agent','Promoter','Photographer','Videographer','Stage Crew','Music Marketing','Mentor / Teacher','Venue Manager'];

export const members = [
  {
    id:'sarah-monroe',
    initials:'SM',
    name:'Sarah Monroe',
    type:'Music Industry Professional',
    role:'Booking Agent',
    location:'New York, NY',
    timezone:'Eastern Time',
    specialty:'Live Music · Independent Artists',
    membership:'Professional',
    verification:'MLI Verified Professional',
    availability:'Available for artist representation',
    responseTime:'Usually responds within 1 day',
    matchScore:94,
    reason:'Matches your booking, location, and live-performance goals.',
    matchReasons:['Booking needs','New York market','Live performance','Blues & Soul','Venue relationships'],
    lookingFor:['Independent artists','Live performers','Tour-ready musicians','Blues and soul acts'],
    availableFor:['Booking','Artist representation','Venue introductions','Showcase strategy'],
    skills:['Artist booking','Live strategy','Venue relations','Tour planning','Contract negotiation'],
    genres:['Blues','Soul','R&B','Jazz','Americana'],
    services:['Artist booking consultation','Showcase lineup strategy','Venue introduction prep'],
    mutuals:['Marcus Lee','Jessica Reed','Nina Foster'],
    sharedGroups:['Live Events & Touring','Venues & Booking'],
    sharedEvents:['CBS Studio Artist Showcase','Music Business Networking Night'],
    tone:'violet',
    state:'Connect',
  },
  { id:'marcus-lee', initials:'ML', name:'Marcus Lee', type:'Music Industry Professional', role:'Producer', location:'Brooklyn, NY', specialty:'Soul · R&B Production', matchScore:91, reason:'Works with independent artists and matches your production needs.', tone:'blue', state:'Connected' },
  { id:'jessica-reed', initials:'JR', name:'Jessica Reed', type:'Business / Venue / Organization', role:'Venue Manager', location:'Manhattan, NY', specialty:'Live Events · Showcases', matchScore:93, reason:'Located in New York and matches your booking needs.', tone:'gold', state:'Accept' },
  { id:'nia-brooks', initials:'NB', name:'Nia Brooks', type:'Artist / Musician', role:'Singer / Songwriter', location:'Queens, NY', specialty:'Soul · Jazz · Live Performance', matchScore:89, reason:'Shares your genres and is looking for a guitarist.', tone:'cyan', state:'Connect' },
];

export const opportunities = [
  { id:1,title:'CBS Studio Artist Showcase',organization:'Music Legacy International',organizerId:'music-legacy',organizerKind:'Posted by MLI',category:'Performance',lookingFor:'Artist / Musician',genre:'Blues · Soul',location:'New York, NY',date:'May 24',deadline:'May 18',compensation:'Paid · $650',compensationType:'Flat fee',mode:'In Person',access:'Pro',trust:'MLI Verified',state:'Featured',activity:'Recommended',slots:'2 performer slots remaining',posted:'May 9',distance:4,closingDays:6,match:95,description:'A curated evening connecting independent artists with booking professionals, venue partners, and music media.',summary:'Showcase your live set in front of booking partners and MLI industry members.',skills:['Guitar','Live Performance','Stage Experience'],matchedSkills:['Guitar','Live Performance'],preferred:['30-minute live set','Performance media','New York availability'],status:'Published',relatedEvent:'CBS Studio Artist Showcase',relatedGroup:'Live Events & Touring',fastTrack:'Book more live performances',relatedPeople:['Sarah Monroe · Booking Agent','Jessica Reed · Venue Manager','Marcus Lee · Producer'],marketplaceServices:['Live & Tour Photography','Performance Video Sessions','Release Campaign Strategy'],reasons:['Artist / Musician','New York area','Blues & Soul','Live-performance goal','Booking opportunities','Pro membership access'] },
  { id:2,title:'Live Blues Guitarist Needed',organization:'The Harbor Room',organizerId:'jessica-reed',organizerKind:'Business Member',category:'Gig',lookingFor:'Artist / Musician',genre:'Blues',location:'Brooklyn, NY',date:'May 18',deadline:'May 14',compensation:'Paid · $450',compensationType:'Flat fee',mode:'In Person',access:'Professional+',trust:'MLI Verified Organization',state:'Closing Soon',activity:'Applied',slots:'1 guitarist position open',posted:'May 10',distance:12,closingDays:2,match:92,description:'Seeking an expressive blues guitarist for a featured weekend set with an established house band.',summary:'A paid local gig matched to your genre, instrument, and booking goals.',skills:['Blues Guitar','Live Performance','Charts'],matchedSkills:['Blues Guitar','Live Performance'],preferred:['Improvisation','Weekend availability'],status:'Published',relatedEvent:'Music Business Networking Night',relatedGroup:'Venues & Booking',fastTrack:'Complete one paid live booking',relatedPeople:['Jessica Reed · Venue Manager','Sarah Monroe · Booking Agent'],marketplaceServices:['Northline Recording Studio','Performance Video Sessions'],reasons:['Matches your primary genre','12 miles from your location','Fits your booking goal','Requires live performance experience'] },
  { id:3,title:'Producer Seeking Female Vocalist',organization:'Northline Sound',organizerId:'marcus-lee',organizerKind:'Professional Member',category:'Collaboration',lookingFor:'Artist / Musician',genre:'Soul · R&B',location:'Remote',date:'Rolling',deadline:'June 1',compensation:'Revenue share',compensationType:'Revenue share',mode:'Remote',access:'All Members',trust:'Professional Member',state:'New',activity:'Saved',slots:'Limited applications',posted:'May 12',distance:0,closingDays:20,match:88,description:'Soul-forward vocalist wanted for a polished three-track collaboration and release campaign.',summary:'Remote recording collaboration with a verified producer and a release plan.',skills:['Vocals','Songwriting','Remote Recording'],matchedSkills:['Vocals','Songwriting'],preferred:['Home recording setup','Soul/R&B credits'],status:'Published',relatedEvent:'Producer Collaboration Session',relatedGroup:'Producers & Engineers',fastTrack:'Build release-ready collaborations',relatedPeople:['Marcus Lee · Producer','Nia Brooks · Singer / Songwriter'],marketplaceServices:['Northline Recording Studio','Release Campaign Strategy'],reasons:['Matches your collaboration interests','Remote participation available','Aligned with your Soul profile'] },
  { id:4,title:'Tour Photographer Needed',organization:'Morrow Artist Co.',organizerId:'morrow-artist-co',organizerKind:'MLI Verified Organization',category:'Crew',lookingFor:'Photographer',genre:'Multi-genre',location:'East Coast',date:'Jun 2-16',deadline:'May 19',compensation:'Paid · Project rate',compensationType:'Project rate',mode:'In Person',access:'Professional+',trust:'MLI Verified',state:'Member Opportunity',activity:'Recommended',slots:'1 photographer position open',posted:'May 8',distance:90,closingDays:7,match:80,description:'Document an emerging artist’s first regional tour across six cities.',summary:'A regional production role for creators building live-music credentials.',skills:['Photography','Tour Experience','Editing'],matchedSkills:['Photography'],preferred:['Low-light concert work','Travel availability'],status:'Published',relatedEvent:'Music Business Networking Night',relatedGroup:'Live Events & Touring',fastTrack:'Expand your live-industry network',relatedPeople:['Jessica Reed · Venue Manager','Sarah Monroe · Booking Agent'],marketplaceServices:['Live & Tour Photography','Northeast Tour Support'],reasons:['Matches your touring interests','Professional member opportunity','Regional travel preference'] },
  { id:5,title:'Independent Artist Marketing Program',organization:'Brightnote Creative',organizerId:'brightnote-creative',organizerKind:'Business Member',category:'Services',lookingFor:'Artist / Musician',genre:'All genres',location:'Remote',date:'Starts Jun 8',deadline:'May 30',compensation:'Member rate',compensationType:'Member rate',mode:'Remote',access:'All Members',trust:'MLI Trusted',state:'MLI Verified',activity:'Recommended',slots:'4 member seats available',posted:'May 11',distance:0,closingDays:18,match:84,description:'A four-week strategy program for artists preparing a release or live-show campaign.',summary:'Get campaign guidance tied to your booking and audience-growth goals.',skills:['Marketing','Release Planning','Content Strategy'],matchedSkills:['Marketing'],preferred:['Upcoming release or show','Profile goals completed'],status:'Published',relatedEvent:'Independent Artist Workshop',relatedGroup:'Promotion & Marketing',fastTrack:'Strengthen your professional presence',relatedPeople:['Sarah Monroe · Booking Agent','Marcus Lee · Producer'],marketplaceServices:['Release Campaign Strategy','Performance Video Sessions'],reasons:['Addresses your promotion needs','Supports your audience-growth goal','Available remotely'] },
  { id:6,title:'Friday Artist Showcase Invitation',organization:'Sarah Monroe',organizerId:'sarah-monroe',organizerKind:'Professional Member',category:'Performance',lookingFor:'Artist / Musician',genre:'Soul · Jazz',location:'Manhattan, NY',date:'May 31',deadline:'May 22',compensation:'Paid · $500',compensationType:'Flat fee',mode:'In Person',access:'Premium',trust:'Invitation',state:'Invitation',activity:'Recommended',slots:'Invitation hold expires soon',posted:'May 12',distance:5,closingDays:10,match:91,description:'A booking-agent invitation to join a Friday showcase lineup for venue partners.',summary:'MLI can facilitate the organizer conversation because your profile is a strong fit.',skills:['Live Performance','Soul Repertoire','Stage Experience'],matchedSkills:['Live Performance','Stage Experience'],preferred:['Recent performance video','Professional profile'],status:'Under Review',relatedEvent:'CBS Studio Artist Showcase',relatedGroup:'Venues & Booking',fastTrack:'Earn priority introductions',relatedPeople:['Sarah Monroe · Booking Agent','Jessica Reed · Venue Manager'],marketplaceServices:['Live & Tour Photography','Release Campaign Strategy'],reasons:['Direct invitation from a recommended booking agent','Matches your Soul profile','Supports your live-performance FastTrack goal'] },
];

export const events = [
  { id:'artist-workshop', day:'14',month:'MAY',date:'May 14',time:'7:00 PM ET',title:'Independent Artist Workshop',category:'Workshop',location:'Online',organizer:'MLI Education',capacity:'120 members',access:'All members',cta:'RSVP' },
  { id:'networking-night', day:'18',month:'MAY',date:'May 18',time:'6:30 PM ET',title:'Music Business Networking Night',category:'Networking Session',location:'Brooklyn, NY',organizer:'MLI New York',capacity:'80 members',access:'Professional+',cta:'RSVP' },
  { id:'cbs-showcase', day:'24',month:'MAY',date:'May 24',time:'8:00 PM ET',title:'CBS Studio Artist Showcase',category:'Live Showcase',location:'Manhattan, NY',organizer:'Music Legacy International',capacity:'150 guests',access:'Pro members only',cta:'Request access' },
  { id:'producer-session', day:'29',month:'MAY',date:'May 29',time:'5:00 PM ET',title:'Producer Collaboration Session',category:'Virtual Meeting',location:'Online',organizer:'Producers & Engineers',capacity:'40 members',access:'Professional+',cta:'RSVP' },
];

export const groups = [
  {id:'welcome',name:'Welcome – Getting Started',description:'Meet the community, learn the platform, and complete your first MLI actions.',members:'12.4K',activity:'Very active',postsToday:42,joined:true,state:'Joined',access:'Public Group',privacy:'Public',admin:'MLI Community Team',bestFor:['New members','Artists','Professionals'],match:0,relevance:'Your first stop for setup, introductions, and platform guidance.',reason:'You are still building your Bridging profile.',moderation:'Published',trend:'New member activity up 18%',people:['Sarah Monroe','Marcus Lee','Jessica Reed'],opportunityIds:[1],eventIds:['artist-workshop'],marketplaceIds:[2],fastTrack:'Complete your first MLI actions.'},
  {id:'independent-artists',name:'Independent Artists',description:'Share releases, find collaborators, and grow sustainable independent careers.',members:'4.8K',activity:'36 posts today',postsToday:36,joined:true,state:'Joined',access:'Public Group',privacy:'Public',admin:'MLI Artist Team',bestFor:['Artists','Songwriters','Fans'],match:88,relevance:'Strong Match',reason:'Matches your artist profile, songwriting skills, and collaboration goals.',moderation:'Published',trend:'Release strategy thread trending',people:['Nia Brooks','Marcus Lee','Sarah Monroe'],opportunityIds:[3,5],eventIds:['artist-workshop'],marketplaceIds:[2,4],fastTrack:'Build professional presence and collaboration momentum.'},
  {id:'producers-engineers',name:'Producers & Engineers',description:'Studio craft, production opportunities, gear, and trusted creative partnerships.',members:'2.6K',activity:'18 posts today',postsToday:18,joined:false,state:'Request to Join',access:'Moderated Group',privacy:'Moderated',admin:'Marcus Lee',bestFor:['Producers','Artists','Engineers'],match:92,relevance:'92% Relevant',reason:'Recommended because production is listed in your skills.',moderation:'Published',trend:'June session openings',people:['Marcus Lee','Nia Brooks','Sarah Monroe'],opportunityIds:[3],eventIds:['producer-session'],marketplaceIds:[1,2],fastTrack:'Find collaborators and release-ready production support.'},
  {id:'live-events-touring',name:'Live Events & Touring',description:'Showcases, touring, booking, production, and everything that happens on stage.',members:'3.1K',activity:'24 posts today',postsToday:24,joined:false,state:'Join',access:'Public Group',privacy:'Public',admin:'Sarah Monroe',bestFor:['Artists','Booking Agents','Venues'],match:91,relevance:'91% Relevant',reason:'Matches your goal to book more live performances.',moderation:'Published',trend:'Touring opportunities on the East Coast',people:['Sarah Monroe','Jessica Reed','Marcus Lee'],opportunityIds:[1,2,4],eventIds:['cbs-showcase','networking-night'],marketplaceIds:[3,5,7],fastTrack:'Build stronger booking relationships.'},
  {id:'music-business-network',name:'Music Business Network',description:'Practical knowledge and relationships for a changing music business.',members:'5.2K',activity:'Very active',postsToday:29,joined:false,state:'Join',access:'Public Group',privacy:'Public',admin:'MLI Business Team',bestFor:['Artists','Managers','Industry Pros'],match:84,relevance:'Strong Match',reason:'Relevant to your business and networking goals.',moderation:'Published',trend:'Contract questions gaining replies',people:['Sarah Monroe','Marcus Lee','Jessica Reed'],opportunityIds:[5,6],eventIds:['networking-night'],marketplaceIds:[2],fastTrack:'Strengthen your music-business confidence.'},
  {id:'venues-booking',name:'Venues & Booking',description:'Connect artists, agents, promoters, and venue decision-makers.',members:'1.9K',activity:'12 posts today',postsToday:12,joined:false,state:'Pro Members Only',access:'Pro Members Only',privacy:'Premium',admin:'Jessica Reed',bestFor:['Artists','Booking Professionals','Venues'],match:94,relevance:'94% Relevant',reason:'Relevant to your booking and networking needs.',moderation:'Published',trend:'Venue partner introductions',people:['Jessica Reed','Sarah Monroe','Marcus Lee'],opportunityIds:[1,2,6],eventIds:['cbs-showcase','networking-night'],marketplaceIds:[7,3],fastTrack:'Create warm booking pathways.'},
  {id:'promotion-marketing',name:'Promotion & Marketing',description:'Campaign strategy, press, content, radio, and audience development.',members:'2.3K',activity:'16 posts today',postsToday:16,joined:false,state:'Request to Join',access:'Moderated Group',privacy:'Moderated',admin:'Brightnote Creative',bestFor:['Artists','Marketers','Managers'],match:89,relevance:'89% Relevant',reason:'Addresses your current audience-growth challenge.',moderation:'Published',trend:'Release campaign budgets',people:['Sarah Monroe','Marcus Lee','Nia Brooks'],opportunityIds:[5],eventIds:['artist-workshop'],marketplaceIds:[2,3,4],fastTrack:'Grow a regional audience with focused promotion.'},
  {id:'fans-audiophiles',name:'Fans & Audiophiles',description:'Discover artists, share listening notes, and find memorable live experiences.',members:'3.7K',activity:'21 posts today',postsToday:21,joined:false,state:'Join',access:'Public Group',privacy:'Public',admin:'MLI Discovery Team',bestFor:['Fans','Artists','Curators'],match:0,relevance:'Community Discovery',reason:'Useful for audience feedback and local discovery.',moderation:'Published',trend:'Live show recommendations',people:['Nia Brooks','Jessica Reed','Sarah Monroe'],opportunityIds:[1],eventIds:['cbs-showcase'],marketplaceIds:[4],fastTrack:'Understand fans and live audience signals.'},
];

export const marketplace = [
  {id:1,title:'Northline Recording Studio',provider:'Marcus Lee',category:'Services',subtype:'Recording Studio',location:'Brooklyn, NY',rating:'Verified · 4.9',tier:'Professional'},
  {id:2,title:'Release Campaign Strategy',provider:'Brightnote Creative',category:'Artist Services',subtype:'Music Marketing Consultant',location:'Remote',rating:'MLI Trusted · 4.8',tier:'Pro'},
  {id:3,title:'Live & Tour Photography',provider:'Maya Ellis',category:'Vendors',subtype:'Photographer',location:'New York, NY',rating:'Verified · 4.9',tier:'Professional'},
  {id:4,title:'Performance Video Sessions',provider:'Framehouse Media',category:'Businesses',subtype:'Videographer',location:'Queens, NY',rating:'Verified · 4.7',tier:'Professional'},
  {id:5,title:'Northeast Tour Support',provider:'Roadcraft Touring',category:'Services',subtype:'Tour Services',location:'East Coast',rating:'MLI Trusted · 4.8',tier:'Pro'},
  {id:6,title:'Small-Batch Artist Merchandise',provider:'Signal Merch Co.',category:'Products',subtype:'Merchandise Vendor',location:'Ships nationwide',rating:'Verified · 4.6',tier:'Professional'},
  {id:7,title:'The Lantern Room',provider:'Jessica Reed',category:'Affiliates',subtype:'Venue Rental',location:'Manhattan, NY',rating:'MLI Partner · 4.9',tier:'Premium'},
];

export const posts = [
  { id:1,initials:'AC',name:'Amara Cole',role:'Artist / Musician',time:'18m',content:'My new single “Stay Until Sunrise” is finally out. This community helped me find the horn players who brought it to life.',tag:'NEW RELEASE',visual:'release' },
  { id:2,initials:'JR',name:'Jessica Reed',role:'Business / Venue / Organization',time:'1h',content:'Booking two opening acts for our June soul series in Manhattan. Looking for strong live performers with 30-minute sets.',tag:'OPPORTUNITY',visual:'venue' },
  { id:3,initials:'ML',name:'Marcus Lee',role:'Music Industry Professional · Producer',time:'3h',content:'Studio B has two evening sessions available next week. Ideal for vocal tracking, songwriting, or pre-production.',tag:'STUDIO',visual:'studio' },
  { id:4,initials:'MLI',name:'Music Legacy',role:'Community Team',time:'Yesterday',content:'Join us for a candid conversation on building relationships that lead to real music-industry opportunities.',tag:'LIVE SESSION',visual:'network' },
];

export const memberships = [
  {name:'Free',price:'$0',annualPrice:'$0',monthlyEquivalent:'$0/mo',line:'Discover the MLI community.',outcome:'Explore MLI.',bestFor:'Exploring the community and getting started.',features:['Public community access','Basic profile','Public events','Basic opportunity browsing'],included:['Community access','Basic profile','Public events','Basic opportunity browsing'],limited:['Connection requests','Messaging','Marketplace browsing'],notIncluded:['Advanced matching','Full FastTrack roadmap','Premium groups','Priority introductions'],unlocks:['Public groups','Public events','Basic opportunity browsing'],accessPreview:['Welcome and public groups','Basic profile','Public event browsing']},
  {name:'Professional',price:'$15',annualPrice:'$153',monthlyEquivalent:'$12.75/mo',line:'Build professional presence.',outcome:'Build visibility.',bestFor:'Members building visibility and professional relationships.',features:['Enhanced professional profile','Expand your industry network','Professional directory visibility','Member groups','Basic opportunity relevance'],included:['Enhanced profile','Professional directory visibility','Member groups','Expanded networking'],limited:['Opportunity relevance','Messaging access','Provider discovery'],notIncluded:['Full FastTrack roadmap','Premium groups','Priority introductions','Exclusive opportunities'],unlocks:['Professional identity badge','Member groups','Expanded connections'],accessPreview:['Enhanced profile tools','Professional directory','Member group access']},
  {name:'Pro',price:'$29',annualPrice:'$295',monthlyEquivalent:'$24.58/mo',line:'Turn goals into opportunity.',outcome:'Accelerate your career growth.',bestFor:'Members actively pursuing opportunities, introductions, and advancement.',features:['Opportunity matching','Full FastTrack access','Get deeper recommendations based on your Bridging profile','Access focused industry groups and curated communities','Get earlier access to selected showcases, networking sessions, and industry events','Recommended for active career growth'],included:['Advanced opportunity matching','Full FastTrack roadmap','Premium groups','Priority event access','Guided weekly actions','Enhanced member matching'],limited:['Priority introductions','Featured placement'],notIncluded:['Private sessions','Concierge-style guidance'],unlocks:['FastTrack roadmap','Advanced opportunity matches','Premium groups','Priority event access'],accessPreview:['FastTrack milestones','Matched opportunities','Premium groups'],recommended:true},
  {name:'Premium',price:'$59',annualPrice:'$602',monthlyEquivalent:'$50.15/mo',line:'Access high-touch support.',outcome:'Access high-touch support.',bestFor:'Members seeking high-touch support, priority visibility, and exclusive access.',features:['Priority introductions','Exclusive industry opportunities','Stand out in member discovery and selected opportunity searches','Private sessions','Concierge-style guidance','Early access to selected opportunities','Priority review / support'],included:['Priority introductions','Exclusive opportunities','Featured visibility','Private sessions','Premium event access','Priority review'],limited:['Concierge guidance availability'],notIncluded:[],unlocks:['Priority introductions','Featured visibility','Exclusive industry opportunities','Private sessions'],accessPreview:['Private sessions','Priority introductions','Featured member visibility']},
];

export const adminActions = ['Edit member email','Change membership level','Approve opportunity','Approve vendor','Create event','Create group','Feature member','Feature opportunity'];
